services: []

argocd:
  url: ""
  token: ""
  repository: ""
  metadata:
    name: "argocd"
    namespace: "argocd"

kafka:
  bootstrap_servers: []
  protocol: "SASL" # PLAIN or SASL
  sasl:
    mechanism: "PLAIN"
    username: ""
    password: ""

logging:
  level: info
